# Generated by Django 4.2.27 on 2025-12-07 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0003_alter_event_id_alter_registration_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="managed_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
