# Generated by Django 4.2.27 on 2025-12-07 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0005_emaillog"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributionGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="managed_distribution_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "events",
                    models.ManyToManyField(
                        blank=True,
                        related_name="distribution_groups",
                        to="events.event",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="distribution_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
