# Generated by Django 4.2.27 on 2025-12-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_distributiongroup_creators_event_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="max_qr_codes",
            field=models.IntegerField(
                blank=True,
                help_text="Límite de códigos QR/registros para este evento. Dejar en blanco para ilimitado.",
                null=True,
            ),
        ),
    ]
