# Generated by Django 4.2.27 on 2025-12-07 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_emaillog_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_logs",
                to="events.registration",
            ),
        ),
    ]
