# Generated by Django 6.0 on 2025-12-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_event_is_public_event_price_alter_accessrequest_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributiongroup",
            name="description",
            field=models.TextField(blank=True, help_text="Descripción del grupo"),
        ),
        migrations.AddField(
            model_name="distributiongroup",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Si es público, cualquiera puede unirse. Si es privado, requiere aprobación.",
            ),
        ),
    ]
