# Generated by Django 6.0 on 2025-12-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_distributiongroup_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributiongroup",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo o imagen del grupo",
                null=True,
                upload_to="group_logos/",
            ),
        ),
        migrations.AlterField(
            model_name="distributiongroup",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Si es público, cualquiera puede unirse. Si es privado, requiere aprobación.",
            ),
        ),
    ]
