# Generated by Django 6.0 on 2026-01-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_distributiongroup_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha límite para inscribirse. Dejar en blanco para ilimitado.",
                null=True,
            ),
        ),
    ]
