# Generated by Django 6.0 on 2026-01-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_event_registration_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="attendee_first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="registration",
            name="attendee_last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="registration",
            name="attendee_type",
            field=models.CharField(
                choices=[
                    ("member", "Fallero"),
                    ("guest", "Invitado"),
                    ("child", "Niño"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
