# Generated by Django 6.0 on 2026-01-10 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_registration_attendee_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="alias",
            field=models.CharField(
                blank=True,
                help_text="Nombre identificativo del QR (ej: Entrada VIP)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="attended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
